git_protocol: ssh
editor: nvim
prompt: enabled
pager: delta -s
aliases:
    co: pr checkout
    al: alias list
    il: issue list
    iv: issue view --comments
    rl: repo list
    rv: repo view
    gv: gist view
    st: status
browser: $BROWSER
