theme = "oxocarbon_dark"
playack_format = "{track} • {artists}\n{album}\n{metadata}"
notify_format = { summary = "{track} • {artists}", body = "{album}" }
copy_command = { command = "wl-copy", args = [] }
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
track_table_item_max_len = 32
enable_media_control = true
enable_cover_image_cache = true
default_device = "spotify-player"
play_icon = "▶"
pause_icon = "⏸"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.5
playback_window_width = 6

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = true
