[[themes]]
name = "oxocarbon_dark"
[themes.palette]
foreground = "#{{colors16.base05}}"
background = "#{{colors16.base00}}"
black = "#{{colors16.base00}}"
blue = "#{{colors16.base0B}}"
cyan = "#{{colors16.base0F}}"
green = "#{{colors16.base0D}}"
magenta = "#{{colors16.base0E}}"
red = "#{{colors16.base0A}}"
white = "#{{colors16.base06}}"
yellow = "#{{colors16.base05}}"
bright_black = "#{{colors16.base0A}}"
bright_blue = "#{{colors16.base0F}}"
bright_cyan = "#{{colors16.base08}}"
bright_green = "#{{colors16.base0D}}"
bright_magenta = "#{{colors16.base0C}}"
bright_red = "#{{colors16.base0A}}"
bright_white = "#{{colors16.base06}}"
bright_yellow = "#{{colors16.base03}}"
selection_background = "#{{colors16.base00}}"
selection_foreground = "#{{colors16.base0F}}"
