[default-applications]
[default-applications.files]
"mimeapps.list" = "~/.config/mimeapps.list"

[wayland]
[wayland.files]
"hypr" = "~/.config/hypr/"
"waybar" = "~/.config/waybar/"
# "eww" = "~/.config/eww/"

[wayland-laptop]
[wayland-laptop.files]
"laptop/hypr-laptop" = "~/.config/hypr/"
# "waybar-laptop" = "~/.config/waybar/"
"laptop/waybar" = "~/.config/waybar/"

[xorg]
[xorg.files]
"bspwm" = "~/.config/bspwm/"
"polybar" = "~/.config/polybar/"
"picom" = "~/.config/picom/"
"sxhkd" = "~/.config/sxhkd/"

[terminal]
depends = ["shell"]
[terminal.files]
"alacritty" = "~/.config/alacritty/"
# "kitty" = "~/.config/kitty/"
"foot" = "~/.config/foot/"
"wezterm" = "~/.config/wezterm/"
"starship" = "~/.config/starship"
# "zellij" = "~/.config/zellij"
[shell]
[shell.files]
"shell/zshrc" = "~/.zshrc"
"shell/zshenv" = "~/.zshenv"
"scripts" = "~/scripts/"

[dev]
[dev.files]
"doom-emacs" = "~/.doom.d/"

[keyboard]
[keyboard.files]
"kmonad" = "~/.config/kmonad/"

[keyboard-laptop]
[keyboard-laptop.files]
"laptop/kmonad-laptop" = "~/.config/kmonad/"

[media]
depends = ["mpv"]
[media.files]
# "ncspot" = "~/.config/ncspot/"
# "newsboat" = "~/.config/newsboat/"
# "youtube-tui" = "~/.config/youtube-tui/"
"ytfzf" = "~/.config/ytfzf/"
"spotify-player" = "~/.config/spotify-player"

[filemanager]
[filemanager.files]
# "ranger" = "~/.config/ranger/"
"xplr" = "~/.config/xplr/"

[launchers]
[launchers.files]
"rofi" = "~/.config/rofi/"
# "wofi" = "~/.config/wofi/"
# "tofi" = "~/.config/tofi/"

[notifications]
[notifications.files]
# "dunst" = "~/.config/dunst/"
"mako" = "~/.config/mako/"

[weeb]
[weeb.files]
# "mangal" = "~/.config/mangal/"
# "animdl" = "~/.config/animdl/"
"jerry" = "~/.config/jerry/"

[other]
[other.files]
"neofetch" = "~/.config/neofetch/"
# "macchina" = "~/.config/macchina/"

[mpv.files]
"mpv/input.conf" = "~/.config/mpv/input.conf"
"mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
"mpv/scripts" = "~/.config/mpv/scripts/"
"mpv/script-opts" = "~/.config/mpv/script-opts/"
"mpv/shaders" = "~/.config/mpv/shaders/"
