[default-applications]
[default-applications.files]
"mimeapps.list" = "~/.config/mimeapps.list"

[wayland]
[wayland.files]
"hypr" = "~/.config/hypr/"
# "waybar" = "~/.config/waybar/"
"eww" = "~/.config/eww/"

[wayland-laptop]
[wayland-laptop.files]
"laptop/hypr-laptop" = "~/.config/hypr/"
# "waybar-laptop" = "~/.config/waybar/"
# "laptop/waybar-laptop" = "~/.config/waybar/"
# "waybar" = "~/.config/waybar/"
"eww" = "~/.config/eww/"

[terminal]
depends = ["shell"]
[terminal.files]
"terminals/alacritty" = "~/.config/alacritty/"
# "kitty" = "~/.config/kitty/"
"terminals/foot" = "~/.config/foot/"
"terminals/wezterm" = "~/.config/wezterm/"
"terminal-tools/starship" = "~/.config/starship"
"terminal-tools/zellij" = "~/.config/zellij"

[shell]
[shell.files]
"shell/zshrc" = "~/.zshrc"
"shell/zshenv" = "~/.zshenv"
"scripts" = "~/scripts/"

[dev]
[dev.files]
"nvim" = "~/.config/nvim/"
"terminal-tools/bat" = "~/.config/bat/"
"lazygit" = "~/.config/lazygit/"
"gh" = "~/.config/gh/"

[media]
depends = ["mpv"]
[media.files]
# "newsboat" = "~/.config/newsboat/"
"mpd" = "~/.config/mpd/"
"mpDris2" = "~/.config/mpDris2/"
"ncmpcpp" = { target = "~/.config/ncmpcpp/", type = "symbolic" }
"spotify-player" = "~/.config/spotify-player"
"zathura" = "~/.config/zathura/"

[filemanager]
[filemanager.files]
# "ranger" = "~/.config/ranger/"
"terminal-tools/xplr" = "~/.config/xplr/"

[launchers]
[launchers.files]
"rofi" = "~/.config/rofi/"
# "wofi" = "~/.config/wofi/"
# "tofi" = "~/.config/tofi/"

[notifications]
[notifications.files]
# "dunst" = "~/.config/dunst/"
"mako" = "~/.config/mako/"

[weeb]
[weeb.files]
# "mangal" = "~/.config/mangal/"
# "jerry" = "~/.config/jerry/"

[other]
[other.files]
"terminal-tools/neofetch" = "~/.config/neofetch/"
"iamb" = "~/.config/iamb/"
# "macchina" = "~/.config/macchina/"

[mpv.files]
"mpv" = "~/.config/mpv/"
"mpv/input.conf" = "~/.config/mpv/input.conf"
"mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
"mpv/scripts" = "~/.config/mpv/scripts/"
"mpv/script-opts" = "~/.config/mpv/script-opts/"
# "mpv/shaders" = "~/.config/mpv/shaders/"
