[helpers]
color_rgb = ".dotter/helpers/color_rgb.rhai"

[default-applications]
[default-applications.files]
"mimeapps.list" = "~/.config/mimeapps.list"

[wayland]
[wayland.files]
"hyprland/hypr" = "~/.config/hypr/"
# "hyprland/bar/waybar" = "~/.config/waybar/"
"hyprland/bar/eww" = "~/.config/eww/"

[wayland-laptop]
[wayland-laptop.files]
"hyprland/laptop/hypr-laptop" = "~/.config/hypr/"
"hyprland/bar/eww" = "~/.config/eww/"

[alacritty.files]
"terminals/alacritty" = "~/.config/alacritty/"
[foot.files]
"terminals/foot" = "~/.config/foot/"
[wezterm.files]
"terminals/wezterm" = "~/.config/wezterm/"
[zellij.files]
"terminal-tools/zellij" = "~/.config/zellij"

[shell.files]
"shell/zshrc" = "~/.zshrc"
"shell/zshenv" = "~/.zshenv"

[scripts.files]
"scripts" = "~/scripts/"

[starship.files]
"shell/starship" = "~/.config/starship"

[nvim.files]
"coding/neovim/nvim" = "~/.config/nvim/"
[nvchad.files]
"coding/neovim/nvchad" = "~/.config/nvchad/"
[vscode.files]
"coding/vscode/settings.json" = "~/.config/Code/User/settings.json"
"coding/vscode/keybindings.json" = "~/.config/Code/User/keybindings.json"

[bat.files]
"terminal-tools/bat" = "~/.config/bat/"
[lazygit.files]
"git/lazygit" = "~/.config/lazygit/"
[gh.files]
"git/gh" = "~/.config/gh/"

[mpd.files]
"media/music/mpd" = "~/.config/mpd/"
[mpdris2.files]
"media/music/mpDris2" = "~/.config/mpDris2/"
[ncmpcpp.files]
"media/music/ncmpcpp" = { target = "~/.config/ncmpcpp/", type = "symbolic" }
[spotify-player.files]
"media/music/spotify-player" = "~/.config/spotify-player"

[mpv.files]
"media/mpv" = "~/.config/mpv/"
"media/mpv/input.conf" = "~/.config/mpv/input.conf"
"media/mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
"media/mpv/scripts" = "~/.config/mpv/scripts/"
"media/mpv/script-opts" = "~/.config/mpv/script-opts/"

[zathura.files]
"media/zathura" = "~/.config/zathura/"

[jerry.files]
# "media/jerry" = "~/.config/jerry/"
[lobster.files]
# "media/lobster" = "~/.config/lobster/"


[xplr.files]
"terminal-tools/xplr" = "~/.config/xplr/"

[rofi.files]
"launchers/rofi" = "~/.config/rofi/"
[rofi.variables]
rofi_font_size = 14

[mako.files]
"notifications/mako" = "~/.config/mako/"

[gtk.files]
"ui/gtk/gtk-2.0" = "~/.config/gtk-2.0/"
"ui/gtk/gtk-3.0" = "~/.config/gtk-3.0/"
[qt5ct.files]
"ui/qt5ct/qt5ct.conf" = "~/.config/qt5ct/qt5ct.conf"
[fonts.files]
"ui/fonts/" = { target = "~/.local/share/fonts/", type = "symbolic" }

[neofetch.files]
"terminal-tools/neofetch" = "~/.config/neofetch/"
[iamb.files]
"communication/iamb" = { target = "~/.config/iamb/", type = "symbolic" }
[copyq.files]
"clipboard/copyq/copyq.conf" = "~/.config/copyq/copyq.conf"

[graphics.variables.colors16]
base00 = "161616"
base01 = "262626"
base02 = "393939"
base03 = "525252"
base04 = "dde1e6"
base05 = "f2f4f8"
base06 = "ffffff"
base07 = "08bdba"
base08 = "3ddbd9"
base09 = "78a9ff"
base0A = "ee5396"
base0B = "33b1ff"
base0C = "ff7eb6"
base0D = "42be65"
base0E = "be95ff"
base0F = "82cfff"

[graphics.variables.font]
family = "Liga SFMono Nerd Font"
size = 14
size_small = 12
huge=30

[graphics.variables.pictures]
profile = "$HOME/dotfiles/pictures/lain-oxocarbon-transparent.png"
black = "$HOME/dotfiles/pictures/lain-oxocarbon-black.png"
