[default-applications]
[default-applications.files]
"mimeapps.list" = "~/.config/mimeapps.list"

[wayland]
[wayland.files]
"hyprland/hypr" = "~/.config/hypr/"
# "hyprland/bar/waybar" = "~/.config/waybar/"
"hyprland/bar/eww" = "~/.config/eww/"

[wayland-laptop]
[wayland-laptop.files]
"hyprland/laptop/hypr-laptop" = "~/.config/hypr/"
"hyprland/bar/eww" = "~/.config/eww/"

[terminal]
depends = ["shell"]
[terminal.files]
"terminals/alacritty" = "~/.config/alacritty/"
"terminals/foot" = "~/.config/foot/"
"terminals/wezterm" = "~/.config/wezterm/"
"terminal-tools/zellij" = "~/.config/zellij"

[shell]
[shell.files]
"shell/zshrc" = "~/.zshrc"
"shell/zshenv" = "~/.zshenv"
"shell/scripts" = "~/scripts/"
"shell/starship" = "~/.config/starship"

[dev]
[dev.files]
"coding/neovim/nvim" = "~/.config/nvim/"
"coding/neovim/nvchad" = "~/.config/nvchad/"
"coding/vscode/settings.json" = "~/.config/Code/User/settings.json"
"coding/vscode/keybindings.json" = "~/.config/Code/User/keybindings.json"
"terminal-tools/bat" = "~/.config/bat/"
"git/lazygit" = "~/.config/lazygit/"
"git/gh" = "~/.config/gh/"

[media]
depends = ["mpv"]
[media.files]
# "newsboat" = "~/.config/newsboat/"
"media/music/mpd" = "~/.config/mpd/"
"media/music/mpDris2" = "~/.config/mpDris2/"
"media/music/ncmpcpp" = { target = "~/.config/ncmpcpp/", type = "symbolic" }
"media/music/spotify-player" = "~/.config/spotify-player"
"media/zathura" = "~/.config/zathura/"

[filemanager]
[filemanager.files]
"terminal-tools/xplr" = "~/.config/xplr/"

[launchers]
[launchers.files]
"launchers/rofi" = "~/.config/rofi/"

[notifications]
[notifications.files]
"notifications/mako" = "~/.config/mako/"

[weeb]
[weeb.files]
# "mangal" = "~/.config/mangal/"
# "jerry" = "~/.config/jerry/"

[ui]
[ui.files]
"ui/gtk/gtk-2.0" = "~/.config/gtk-2.0/"
"ui/gtk/gtk-3.0" = "~/.config/gtk-3.0/"
"ui/gtk/gtk-4.0" = "~/.config/gtk-4.0/"
"ui/qt5ct/qt5ct.conf" = "~/.config/qt5ct/qt5ct.conf"

[other]
[other.files]
"terminal-tools/neofetch" = "~/.config/neofetch/"
"communication/iamb" = "~/.config/iamb/"
"clipboard/copyq/copyq.conf" = "~/.config/copyq/copyq.conf"

[mpv.files]
"media/mpv" = "~/.config/mpv/"
"media/mpv/input.conf" = "~/.config/mpv/input.conf"
"media/mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
"media/mpv/scripts" = "~/.config/mpv/scripts/"
"media/mpv/script-opts" = "~/.config/mpv/script-opts/"
