[colors]
background = '#{{colors16.base00}}'
foreground = '#{{colors16.base06}}'
cursor_bg = '#{{colors16.base06}}'
cursor_border = '#{{colors16.base06}}'
cursor_fg = '#{{colors16.base00}}'

ansi = [
    '#{{colors16.base01}}',
    '#{{colors16.base0A}}',
    '#{{colors16.base0D}}',
    '#{{colors16.base0C}}',
    '#{{colors16.base0B}}',
    '#{{colors16.base0C}}',
    '#{{colors16.base08}}',
    '#{{colors16.base04}}',
]
brights = [
    '#{{colors16.base02}}',
    '#{{colors16.base0A}}',
    '#{{colors16.base0D}}',
    '#{{colors16.base0C}}',
    '#{{colors16.base0B}}',
    '#{{colors16.base0C}}',
    '#{{colors16.base08}}',
    '#{{colors16.base06}}',
]

[colors.tab_bar]
background = "#{{colors16.base01}}"

[colors.tab_bar.active_tab]
bg_color = '#{{colors16.base00}}'
fg_color = '#{{colors16.base06}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#{{colors16.base01}}'
fg_color = '#{{colors16.base06}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#{{colors16.base01}}'
fg_color = '#{{colors16.base06}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'


[metadata]
name = 'Oxocarbon Dark'
origin_url = 'https://github.com/nyoom-engineering/base16-oxocarbon'
